# Generated by Django 3.0.3 on 2020-02-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20200219_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
