# Generated by Django 3.0.3 on 2020-02-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_converter_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converter',
            name='file',
        ),
    ]
